name: CI

on: [push, pull_request]

jobs:
    industrial_ci:
        strategy:
            matrix:
                env:
                    - {ROS_DISTRO: melodic, ROS_REPO: testing, CMAKE_ARGS: '-DCMAKE_CXX_FLAGX="-Wall -Wextra -Wpedantic -Werror"'}
                    - {ROS_DISTRO: melodic, ROS_REPO: main, CMAKE_ARGS: '-DCMAKE_CXX_FLAGX="-Wall -Wextra -Wpedantic -Werror"'}
                    - {ROS_DISTRO: noetic, ROS_REPO: testing, CMAKE_ARGS: '-DCMAKE_CXX_FLAGX="-Wall -Wextra -Wpedantic -Werror"'}
                    - {ROS_DISTRO: noetic, ROS_REPO: main, CMAKE_ARGS: '-DCMAKE_CXX_FLAGX="-Wall -Wextra -Wpedantic -Werror"'}
                    - {ROS_DISTRO: melodic, CLANG_FORMAT_CHECK: file, CLANG_FORMAT_VERSION: '6.0'}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: 'ros-industrial/industrial_ci@master'
              env: ${{matrix.env}}

